### ISSUE TITLE
When using Flow and peer dependencies are not respected

### ISSUE THREAD

**Issue by dej611** [ImprontaAdvance/eslint-config#12]
When using Flow the configuration requires to latest babel-eslint version (`8.x.x`) but the required peer dependency in the package here is the previous one.

```
warning " > @improntaadvance/eslint-config@0.8.3" has incorrect peer dependency "babel-eslint@^7.2.3".
```

There are no conflicts using the newer version of babel-eslint so far (we've been using it for a while), so bump up that vrsion.

**Comment by Takeno** [comment]
Flow is not supported anymore.
